package fr.cridf.babylone14166.webservice.dto;

public class ConseillerDto {
    // MANDATURE	NOM	ACTIVITE_PROF	ADRESSE	VILLE	CODE_POSTAL	DATE_NAISSANCE	GROUPE_COURT	GROUPE_POLITIQUE
    // LISTE_COURT	LISTE_ELECTORALE	NB_ENFANTS	NOM_JEUNE_FILLE	AUTRES_MANDATS	SITUATION_FAMILIALE	TELEPHONE
    // FAX	MAIL	VALID	CODE_DEP_ELECTION	DEP_ELECTION	PRENOM	CIVILITE	VILLE_NAISSANCE	PROFESSION
    // UID_CONSEILLER	DISTINCTIONS	DESCRIPTION	JPEGPHOTO	ST	COMMISSIONS	DESIGNATIONS	FONCTION_EXECUTIF
    // PHONETIQUE	TWITTER	FACEBOOK	SITE_INTERNET	BLOG	AUTRE
}
