package fr.cridf.babylone14166.webservice.dto;

public class EnsembleDto {
    //MANDATURE	UID_ENSEMBLE	LIB_COURT	DATE_CREATION	TYPE	TYPE_COMMISSION	NB_MEMBRE	NB_TITULAIRE
    // NB_SUPPLEANT	VALID	LIB_LONG	ST	DATE_FIN	DESCRIPTION	CODE_RNE	DEPARTEMENT	MOTIF_FIN
    // SECTEUR	TELEPHONE	FAX	ADRESSE	CODE_POSTAL	VILLE	STATUS	MAIL	PHONETIQUE
}
