package fr.cridf.babylone14166.webservice.dto;

public class MembreDto {
    // UID_MEMBRE	MANDATURE	UID_CONSEILLER	UID_ENSEMBLE	TYPE	DATE_DEBUT	DATE_FIN	NUMERO_NOMINATION
    // STATUS	NOMINATION	ST	FONCTION	BUREAU	MOTIF_FIN	DATE_NOMINATION	DESCRIPTION
}
